//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daniel_Tueros
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public int AL1_CCODIGO { get; set; }
        public string AL1_CPATERNO { get; set; }
        public string AL1_CMATERNO { get; set; }
        public string AL1_CNOMBRES { get; set; }
        public string AL1_CDIRECCION { get; set; }
        
        public System.DateTime AL1_FECHA { get; set; }
        public Nullable<int> AL1_NEDAD { get; set; }
        
        public int edad
        {
            get
            {
                {
                    DateTime hoy = DateTime.Today;
                    int edad = hoy.Year - AL1_FECHA.Year;
                    if (AL1_FECHA > hoy.AddYears(-edad))
                    {
                        edad--;
                    }
                    return edad;
                }
            }
        }
    }
}
